# @package _global_

# SORAN DATASET
dset:
  wav: /media/data/Dataset/SORAN_DATASET
  samplerate: 44100
  channels: 2
  segment: 2
  sources: ['BALUNGAN', 'BONANG_BARUNG', 'KENDHANG', 'KEMPUL_GONG', 'KETHUK_KENONG', 'SLENTHEM']

solver: spec

model: umx

umx:
  channels: 32

misc:
  num_workers: 0

test:
  save: True
  best: True
  workers: 0
  every: 10

augment:
  shift_same: false
  repitch:
    proba: 0.2
    max_tempo: 12
  remix:
    proba: 1
    group_size: 4
  scale:
    proba: 1
    min: 0.25
    max: 1.25
  flip: true

epochs: 20
batch_size: 4
weights: [1., 1., 1., 1., 1., 1.]
save_every: 1

# Hydra config
hydra:
  job_logging:
    formatters:
      colorlog:
        datefmt: "%m-%d %H:%M:%S"